// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.WebApi.Angular.Data;

#nullable disable

namespace OnlineShop.WebApi.Angular.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220914175331_Create-Shopping-Cart")]
    partial class CreateShoppingCart
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ffdeb4a-2b28-4fc8-9d41-30bd16984923"),
                            ConcurrencyStamp = "2394e4ac-4218-4950-afbd-50ffce013ac2",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("08d68e62-6e3b-4cf4-bfb0-49d59f670a5b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3da4a16d-6c68-4846-8681-48b0a74134ed",
                            Email = "admin@email.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEJ+TRXRjZZ8K5Rkw9XxcIRT4AWki52/WFaP+U0GU2LsNlVfM88SQ+RRg3cCLko5Qmg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b40b766-f054-455d-be9d-30f22a80b48c"),
                            Description = "New Balance Athletics, Inc., best known as simply New Balance, is one of the world's major sports footwear and apparel manufacturers. Based in Boston, Massachusetts, the multinational corporation was founded in 1906 as the New Balance Arch Support Company. ",
                            ImgUrl = "",
                            Name = "New Balance",
                            Title = "New Balance"
                        },
                        new
                        {
                            Id = new Guid("47fc022b-672d-4869-835f-84eef087f735"),
                            Description = "Hoka One One is an athletic shoe company originating in France that designs and markets running shoes.",
                            ImgUrl = "",
                            Name = "HOKA ONE ONE",
                            Title = "HOKA ONE ONE"
                        },
                        new
                        {
                            Id = new Guid("2c46fc6a-2b53-4ff3-bc2d-6388e82f9bdc"),
                            Description = "Under Armour, Inc. is an American sports equipment company that manufactures footwear, sports and casual apparel.",
                            ImgUrl = "",
                            Name = "Under Armour",
                            Title = "Under Armour"
                        },
                        new
                        {
                            Id = new Guid("18913488-917c-4748-b19f-37bb1b03b889"),
                            Description = "Salomon Group is a French sports equipment manufacturing company based in Annecy, France. It was founded in 1947 by François Salomon in the heart of the French Alps and is a major brand in outdoor sports equipment.",
                            ImgUrl = "",
                            Name = "Salomon Group",
                            Title = "Salomon Group"
                        });
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("CartId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e19b211-dc2a-490e-905d-a0420032cc57"),
                            Description = "A shoe is an item of footwear intended to protect and comfort the human foot. Shoes are also used as an item of decoration and fashion. The design of shoes has varied enormously through time and from culture to culture, with form originally being tied to function.",
                            ImgUrl = "",
                            Name = "Shoes",
                            Title = "Shoes"
                        },
                        new
                        {
                            Id = new Guid("9da89049-b1fd-4074-8fbd-c9d62e58c59b"),
                            Description = "A T-shirt, or tee, is a style of fabric shirt named after the T shape of its body and sleeves. Traditionally, it has short sleeves and a round neckline, known as a crew neck, which lacks a collar. T-shirts are generally made of a stretchy, light, and inexpensive fabric and are easy to",
                            ImgUrl = "",
                            Name = "T-Shirts",
                            Title = "T-Shirts"
                        },
                        new
                        {
                            Id = new Guid("e35a55c3-63f6-40dc-becf-d980367b36a6"),
                            Description = "Shorts are a garment worn over the pelvic area, circling the waist and splitting to cover the upper part of the legs, sometimes extending down to the knees but not covering the entire length of the leg.",
                            ImgUrl = "",
                            Name = "Shorts",
                            Title = "Shorts"
                        },
                        new
                        {
                            Id = new Guid("db1c223f-de21-48ff-a7d7-1470e5587d1f"),
                            Description = "A jacket is a garment for the upper body, usually extending below the hips. A jacket typically has sleeves, and fastens in the front or slightly on the side. A jacket is generally lighter, tighter-fitting, and less insulating than a coat, which is outerwear.",
                            ImgUrl = "",
                            Name = "Jacket",
                            Title = "Jacket"
                        });
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.CategoryProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CategoryProduct");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("0966f6c6-505a-46bc-b424-d75dd3c7f85b"),
                            CategoryId = new Guid("0e19b211-dc2a-490e-905d-a0420032cc57")
                        },
                        new
                        {
                            ProductId = new Guid("441af150-fdea-4784-9c99-057fd4a73d60"),
                            CategoryId = new Guid("0e19b211-dc2a-490e-905d-a0420032cc57")
                        },
                        new
                        {
                            ProductId = new Guid("76024e75-ada1-448c-9dcf-5b620eb01e52"),
                            CategoryId = new Guid("0e19b211-dc2a-490e-905d-a0420032cc57")
                        },
                        new
                        {
                            ProductId = new Guid("435bc615-f43f-497d-a2c6-51b9ce7fd4af"),
                            CategoryId = new Guid("9da89049-b1fd-4074-8fbd-c9d62e58c59b")
                        },
                        new
                        {
                            ProductId = new Guid("6f43d008-a379-4dfe-b7e1-834c9974cefb"),
                            CategoryId = new Guid("9da89049-b1fd-4074-8fbd-c9d62e58c59b")
                        },
                        new
                        {
                            ProductId = new Guid("5c05add7-4333-4f5d-8182-04203fde6941"),
                            CategoryId = new Guid("9da89049-b1fd-4074-8fbd-c9d62e58c59b")
                        });
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0966f6c6-505a-46bc-b424-d75dd3c7f85b"),
                            BrandId = new Guid("47fc022b-672d-4869-835f-84eef087f735"),
                            Description = "Hoka Tecton X Trail Running Shoes Named after the earth's tectonic plates, which inspired its revoluntionary parallel carbon fiber plate technology, the new Hoka Tecton X is poised to unleash a seismic shift in trail running. Built for speed, with a Profly X midsole bolstered by a Vibram Megagrip Litebase outsole, the Tecton X is Hoka's first trail shoe to incorporate dynamically propulsive,dual parallel carbon fiber plates.",
                            ImgUrl = "",
                            Name = "HOKA TECTON X",
                            Price = 174.0,
                            Title = "HOKA TECTON X TRAIL RUNNING SHOES - AW22"
                        },
                        new
                        {
                            Id = new Guid("441af150-fdea-4784-9c99-057fd4a73d60"),
                            BrandId = new Guid("4b40b766-f054-455d-be9d-30f22a80b48c"),
                            Description = "New Balance Fresh Foam X Hierro V7 Trail Running ShoesPeople love the idea of adventure in the great outdoors,but there's more to the natural landscape than fresh air and scenic views. For those who take going off the beaten path literally, there's the Fresh Foam X Hierro, a dedicated,off - road application of our best running technology.",
                            ImgUrl = "",
                            Name = "NEW BALANCE FRESH FOAM",
                            Price = 129.0,
                            Title = "NEW BALANCE FRESH FOAM X HIERRO V7 TRAIL RUNNING SHOES - SS22"
                        },
                        new
                        {
                            Id = new Guid("76024e75-ada1-448c-9dcf-5b620eb01e52"),
                            BrandId = new Guid("2c46fc6a-2b53-4ff3-bc2d-6388e82f9bdc"),
                            Description = "Under Armour Flow Velociti Wind 2 Running ShoesThere's fast, and then there's UA Flow fast.Lightweight,rubberless,and durable,our newest cushioning gives a close - to - the - ground,grippy feeling of speed.The kind of speed that feels like you've got the wind at your back.",
                            ImgUrl = "",
                            Name = "UNDER ARMOUR FLOW VELOCITI WIND",
                            Price = 139.0,
                            Title = "UNDER ARMOUR FLOW VELOCITI WIND 2 RUNNING SHOES - SS22"
                        },
                        new
                        {
                            Id = new Guid("435bc615-f43f-497d-a2c6-51b9ce7fd4af"),
                            BrandId = new Guid("47fc022b-672d-4869-835f-84eef087f735"),
                            Description = "Higher State Seamfree Running T-ShirtRun with confidence and no distractions with the Higher State Seamfree Running T - Shirt.The Higher State Seamfree Running T - Shirt is a lightweight running tee with a seamfree construction for comfort and freedom of movement without the risk of irritation or unnecessary heavy materials holding you back.The lightweight material offers superior breathability allowing airflow in and out of the t - shirt easily.This prevents warm air from building up within the t - shirt and is replaced with cooler, fresher air.As you begin to sweat, the material works hard to wick away moisture keeping you feeling dry and comfortable and the top light.The back features further ventilation panels which help to keep your temperature down as your run intensifies.Lastly, the short sleeves are specially designed to allow a wide range of movement in all directions and the fit of the tee gives a soft next to skin feel without feeling too restrictive.",
                            ImgUrl = "",
                            Name = "HIGHER STATE RUNNING T-SHIRT",
                            Price = 9.0,
                            Title = "HIGHER STATE SEAMFREE RUNNING T-SHIRT"
                        },
                        new
                        {
                            Id = new Guid("6f43d008-a379-4dfe-b7e1-834c9974cefb"),
                            BrandId = new Guid("18913488-917c-4748-b19f-37bb1b03b889"),
                            Description = "Salomon S/LAB NSO Running T-ShirtA lightweight running tee with NSO Self Activated Energy technology.The S / LAB NSO TEE harnesses next generation oxide mineral technology.",
                            ImgUrl = "",
                            Name = "SALOMON S/LAB ",
                            Price = 29.0,
                            Title = "SALOMON S/LAB NSO RUNNING T-SHIRT"
                        },
                        new
                        {
                            Id = new Guid("5c05add7-4333-4f5d-8182-04203fde6941"),
                            BrandId = new Guid("4b40b766-f054-455d-be9d-30f22a80b48c"),
                            Description = "New Balance Accelerate T-ShirtRun with comfort and confidence in the Accelerate T - shirt from New Balance.Signature NB Dry technology eradicates sweat and moisture while reflective details keep you visible in low light.",
                            ImgUrl = "",
                            Name = "NEW BALANCE ACCELERATE RUNNING",
                            Price = 139.0,
                            Title = "NEW BALANCE ACCELERATE RUNNING T-SHIRT - SS22"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.CategoryProduct", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.Category", "Category")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OnlineShop.WebApi.Angular.Models.Product", "Product")
                        .WithMany("CategoryProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.WebApi.Angular.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Category", b =>
                {
                    b.Navigation("CategoryProducts");
                });

            modelBuilder.Entity("OnlineShop.WebApi.Angular.Models.Product", b =>
                {
                    b.Navigation("CategoryProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
